[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
package = "@netlify/plugin-nextjs"

[env.production]
NEXT_PUBLIC_FIREBASE_API_KEY = "AIzaSyBWChOAPblo92QjLK7dQUaOfVxzlAKLLrQ"
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN = "novo-finaceiro-versa.firebaseapp.com"
NEXT_PUBLIC_FIREBASE_PROJECT_ID = "novo-finaceiro-versa"
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET = "novo-finaceiro-versa.firebasestorage.app"
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID = "276914720870"
NEXT_PUBLIC_FIREBASE_APP_ID = "1:276914720870:web:f5f8f16bd5a15328a35da7"
